# Writes BuildStamp.h. Invoked every build so the stamp tracks the binary,
# not the last cmake configure.

if (NOT DEFINED STAMP_OUT)
    message (FATAL_ERROR "GenerateBuildStamp.cmake: STAMP_OUT is required")
endif()

if (NOT DEFINED THE89TH_VERSION)
    set (THE89TH_VERSION "0.0.0")
endif()

string (TIMESTAMP THE89TH_BUILD_STAMP "%Y-%m-%d %H:%M:%S")

set (THE89TH_GIT_HASH "unknown")
if (DEFINED THE89TH_SOURCE_DIR)
    execute_process (
        COMMAND git rev-parse --short HEAD
        WORKING_DIRECTORY "${THE89TH_SOURCE_DIR}"
        OUTPUT_VARIABLE THE89TH_GIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    if (THE89TH_GIT_HASH STREQUAL "")
        set (THE89TH_GIT_HASH "unknown")
    endif()
endif()

file (WRITE "${STAMP_OUT}"
"#pragma once

// Generated by cmake/GenerateBuildStamp.cmake — do not edit.
#define THE89TH_VERSION     \"${THE89TH_VERSION}\"
#define THE89TH_BUILD_STAMP \"${THE89TH_BUILD_STAMP}\"
#define THE89TH_GIT_HASH    \"${THE89TH_GIT_HASH}\"
")
